#!/bin/bash
# @Time    : 2023/08/01 19:17
# @Author  : Logan.Jin | www.loganjin.cn
# @FileName: shapshot
# @Annotation: 转载请保留来源

backup(){
  snapshot_name=${1}
  file_name="${2}_`date +"%Y%m%d-%H%M%S"`.tar.gz"
  backup_path=${3}
  filter_paths=${@:4}
  filter_all=''
  for path in $filter_paths;
  do
    filter_all="${filter_all} --exclude=${path} "
  done
  echo "The current time is `date +"%Y%m%d-%H%M%S"`.Start to backup the ${backup_path} directory, ignoring ${filter_paths}."
  tar -g ${snapshot_name} -zcpf ${file_name} ${filter_all} ${backup_path}
  echo "${backup_path} directory backup is complete, backup file absolute path ${file_name}. current time is `date +"%Y%m%d-%H%M%S"`."
}

restore(){
  snapshot_name=${1}
  file_name=${2}
  restore_path=${3}
  restore_dirs=${@:4}
  restore_all=''
  for dir in $restore_dirs;
  do
    restore_all="${restore_all} ${dir} "
  done
  echo "The current time is `date +"%Y%m%d-%H%M%S"`.The ${restore_path} directory starts to be restored,The restore list is ${restore_dirs}."
  tar -g ${snapshot_name} -zxpf ${file_name} -C ${restore_path} ${restore_all}
  rm -rf ${file_name}
  echo "Backup file ${file_name} is restored."
  restorecon -Rv ${restore_path}
  echo "Restore directory ${restore_path}SELinux file properties are restored, restart takes effect. current time is `date +"%Y%m%d-%H%M%S"`."
}

copy(){
  local_path=${1}
  target_host=${2}
  target_path=${3}
  echo "The current time is `date +"%Y%m%d-%H%M%S"`. Copy the local ${local_path} directory to \"$target_host\" $target_path directory on the server."
  rsync -avzu --progress "${local_path}" root@"$target_host":"$target_path"
  echo "Copy complete, current time is `date +"%Y%m%d-%H%M%S"`"
}

clear(){
  path=${1}
  days=${2}
  find "${path}" -mtime +${days} -type f -name "*.tar.gz" -delete
  echo "The files in the ${path} directory have been cleared ${days} days ago."
}

$@
